{% set name = "prettytable" %}
{% set version = "3.12.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: f04b3e1ba35747ac86e96ec33e3bb9748ce08e254dc2a1c6253945901beec804

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - pip
    - python >=3.8
    - hatchling
    - hatch-vcs
  run:
    - python >=3.8
    - wcwidth
  run_constrained:
    - ptable >=9999

test:
  imports:
    - prettytable
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/prettytable/prettytable
  license_file: LICENSE
  license: BSD-3-Clause
  summary: A simple Python library for easily displaying tabular data in a visually appealing ASCII table format

extra:
  recipe-maintainers:
    - anguslees
    - licode
    - ericpre
