{% set name = "prettytable" %}
{% set version = "3.10.2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 29ec6c34260191d42cd4928c28d56adec360ac2b1208a26c7e4f14b90cc8bc84

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - pip
    - python >=3.8
    - hatchling
    - hatch-vcs
  run:
    - python >=3.8
    - wcwidth
  run_constrained:
    - ptable >=9999

test:
  imports:
    - prettytable

about:
  home: https://github.com/jazzband/prettytable
  license_file: LICENSE
  license: BSD-3-Clause
  summary: A simple Python library for easily displaying tabular data in a visually appealing ASCII table format

extra:
  recipe-maintainers:
    - anguslees
    - licode
    - ericpre
