{% set name = "prettytable" %}
{% set version = "3.16.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 3c64b31719d961bf69c9a7e03d0c1e477320906a98da63952bc6698d6164ff57

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - hatchling >=1.27
    - hatch-vcs
  run:
    - python >={{ python_min }}
    - wcwidth
  run_constrained:
    - ptable >=9999

test:
  imports:
    - prettytable
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/prettytable/prettytable
  license_file: LICENSE
  license: BSD-3-Clause
  summary: A simple Python library for easily displaying tabular data in a visually appealing ASCII table format

extra:
  recipe-maintainers:
    - anguslees
    - licode
    - ericpre
