{% set name = "prettytable" %}
{% set version = "1.0.0" %}
{% set hash = "98a3b74b1980e6a9392498e3a2a5406f6bd836f412843c2be23d9c88671747ac" %}
{% set build = 0 %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ hash }}

build:
  noarch: python
  number: {{ build }}
  script: {{ PYTHON }} -m pip install . --no-deps -vv


requirements:
  host:
    - pip
    - python
    - setuptools
    - setuptools_scm
    - wcwidth

  run:
    - python
  run_constrained:
    - ptable >=9999

test:
  imports:
    - prettytable

about:
  home: https://github.com/jazzband/prettytable
  license_file: COPYING
  license: BSD 3-Clause
  license_family: BSD
  summary: A simple Python library for easily displaying tabular data in a visually appealing ASCII table format

extra:
  recipe-maintainers:
    - anguslees
    - pmlandwehr
    - licode
